### PR TITLE
feat: add and commit changes

### PR DESCRIPTION
**Pull request by esacteksab**
## [Investigate options for GHA to apply terraform-docs changes to open PRs that change formatting](https://trello.com/c/wMX33z55/178-investigate-options-for-gha-to-apply-terraform-docs-changes-to-open-prs-that-change-formatting)

Changes proposed in this pull request:

- adds `add-and-commit` GitHub Action from [EndBug](https://github.com/EndBug/add-and-commit)

### CODE REVIEW

**Comment by esacteksab** [comment]
[Investigate options for GHA to apply terraform-docs changes to open PRs that change formatting](https://trello.com/c/wMX33z55/178-investigate-options-for-gha-to-apply-terraform-docs-changes-to-open-prs-that-change-formatting)

**Review by rpdelaney — COMMENTED** [review]
1. Does this apply _all_ pre-commit changes? Do we want that? Maybe we do! Hmm...
2. Now that we have an easy way to update CI checks in bulk across the org, we should feel free to create separate shared actions rather than packing many things into `validate`. What do you think?

**Comment by esacteksab** [comment]
> 1. Does this apply _all_ pre-commit changes? Do we want that? Maybe we do! Hmm...
> 
>     2. Now that we have an easy way to update CI checks in bulk across the org, we should feel free to create separate shared actions rather than packing many things into `validate`. What do you think?

1) The `add: *.md` will only add markdown files. What I feel like we experience the most and the Trello card speaks to specifically is when a Terraform provider or Terraform version changes resulting in the `README.md` being updated as a result. This should address this. 

2) Agreed. As I was looking at `validate.yml` this morning, it felt like you could have a general `validate.yaml` and then a `validate-go.yml` and a `validate-python.yml`, etc. etc. Because projects with no Go doing `gorelease` things is annoying AF.

**Review by rpdelaney — APPROVED** [review]
I'll approve as-is. If you feel excited about making separate actions then go for it. If not, this is worth trying in its current form. Let's test it out somewhere once merged though? To make sure we didn't break all the repos xd

**Comment by esacteksab** [comment]
Closed in favor of #20

**Pull request closed without merging**
